### ISSUE TITLE
Spike: Implement unchained websockets

### ISSUE THREAD

**Issue by 0xdef1cafe** [shapeshift/unchained#10]
This needs to be discussed and scoped out by @kaladinlight before work starts.

Please update the ticket with acceptance criteria when it's known.

**Comment by mvpratt** [comment]
what do you think of changing the title of this to be a Spike, since we haven't decided on the API yet? @0xdef1cafe @kaladinlight

**Comment by Orion-9R** [comment]
Is this to consume websocket data or to provide a data source? 

We're discussing adding websockets to THORChain Midgard which could provide parsed thorchain transactions. 
Having a scoped API on the unchained side would help inform things on our end too.

**Comment by kaladinlight** [comment]
@Orion-9R This would be websockets pushing data to a client to provide a data source.

There is an ingestion pipeline that breaks down and parses transactions into more digestible format.

We do have openapi docs for the current unchained API at: https://api.ethereum.shapeshift.com/docs
