### ISSUE TITLE
Thorchain upgrade prep

### ISSUE THREAD

**Issue by 0xean** [shapeshift/unchained#1078]
https://discord.com/channels/838986635756044328/929872517794000986/1314315675392544810

@kaladinlight to tackle

**Comment by kaladinlight** [comment]
https://gitlab.com/thorchain/thornode/-/blob/develop/app/upgrades/v3/README.md?ref_type=heads

**Comment by kaladinlight** [comment]
Prep was done, though plenty of fallout after in flight. Closing this a complete though
