### ISSUE TITLE
Cosmos-SDK: Support disparate package versions

### ISSUE THREAD

**Issue by kaladinlight** [shapeshift/unchained#266]
- Thorchain is still on v0.42.1 and currently broken against the new version we are using. Going to leave broken for now as cosmos and osmosis are priority and list a couple possible strategies to fix:
    - Update thorchain to use new cosmos-sdk version (friction with thorchain)
    - Fork cosmos-sdk and thorchain to use a versioned module name that thorchain can use and then not conflict with our local cosmos-sdk import ie. github.com/cosmos/cosmos-sdk/v42. (continued maintenance)
    - Suggest cosmos start utilizing versioned modules to allow multiple version imports in a project and update thorchain to use versioned module name (friction with cosmos)
    - See how go.work files might be leveraged (workspaces) when golang 1.18 is released here in the near future, current estimate was feb 2022. (unknown time frame and understanding if this would work in the monorepo setup)
    - Break out our `pkg/cosmos` into it's own repo/module that can be imported in unchained and require all cosmos-sdk usage to exist in there. Not tested, but I believe this would allow mutliple versions of indirect dependencies. (requires separate module and forces all cosmos-sdk logic to be encapsulated otherwise same problem arises)

**Comment by kaladinlight** [comment]
This may no longer be an issue with the upcoming thorchain hardfork detailed here: https://lively-router-cb2.notion.site/Cosmos-v0-45-Migration-Guide-for-THORChain-Interfaces-1d140176017b433da79f77200904fbb6

**Comment by asamere** [comment]
we moved this to backlog as I agree the urgency on this has plummeted with thorchain upgrading

**Comment by 0xdef1cafe** [comment]
will be answered with work to support RUNE

**Comment by kaladinlight** [comment]
Confirmed working with new thorchain package version
