### ISSUE TITLE
Tx Parser: Refactor to be pure functions

### ISSUE THREAD

**Issue by kaladinlight** [shapeshift/unchained#268]
Currently the parsers mutate the transfers array and aggregate values as it parses the various parts of a transaction. Mutating values like this may result in unintended side effects. To prevent this possibility, pure functions can be used instead.

AC:
- Refactor `aggregateTransfer` to be a pure function
- Make a pure function to assign transfers

**Comment by 0xApotheosis** [comment]
❤️
