### ISSUE TITLE
Parsing uniV2 "stake"/"unstake" transactions

### ISSUE THREAD

**Issue by stackedq** [shapeshift/unchained#347]
### Overview

Currently, the transaction type of uniV2 "stake" is returned as "Send". We either need a specific type for this kind of transaction or at least some information for a better representation at the `web` repo.
The same thing happens for uniV2 "Unstake' transactions.

### Reference

Probably these problems occur in: 

- https://github.com/shapeshift/unchained/blob/develop/node/packages/client/src/ethereum/parser/uniV2.ts#L81
- https://github.com/shapeshift/unchained/blob/develop/node/packages/client/src/ethereum/parser/uniV2.ts#L109

### Acceptance Criteria

- uniV2 "Stake" transaction type should be marked as "Stake"
- uniV2 "Unstake" transaction type should be marked as "Unstaked"

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by kaladinlight** [comment]
@stackedq This would fall under the same metadata additions that were added for yearn tx parsing. The base transfer payloads are accurate in that value is being sent/received based on stake/unstake. All we need to do is tap into `parsedTx.data` and tag it with the appropriate method name and parser name `uniV2`.

See https://github.com/shapeshift/unchained/blob/develop/node/packages/client/src/ethereum/parser/yearn.ts for reference. This will ensure that we are still calculating balances correctly via the transfers array and also have the necessary information in the `data` field to chose the correct tx row to render. As there are multiple methods for staking and unstaking, we could additionally add a more generic `action` type value in addition to the specific method name if that would be helpful client side.

**Comment by stackedq** [comment]
@0xdef1cafe Would you please share your thoughts?

**Comment by kaladinlight** [comment]
> @0xdef1cafe Would you please share your thoughts? We can still achieve a separate tx row renderer in web by using `addLiquidityEth` and `removeLiquidityEth` with this suggested approach.

After looking at how the transaction rows are being rendered currently and talking with @elmutt, just relying on the current `parser` and `method` should be sufficient so we can keep things simple. We can talk more about the need for a higher level `action` bucket if needed further down the road.

**Comment by stackedq** [comment]
@kaladinlight Currently I think there are multiple txs for a stake action right?
We probably need to pack those transactions in one for web, because currently the staking tx has only one asset (in my case LP Fox), but the staking is done using two different assets (eth and lp fox).

**Comment by kaladinlight** [comment]
> @kaladinlight Currently I think there are multiple txs for a stake action right? We probably need to pack those transactions in one for web, because currently the staking tx has only one asset (in my case LP Fox), but the staking is done using two different assets (eth and lp fox).

The parser should only produce one single transaction object per transaction that encompasses multiple possible transfers (ie. send eth and fox, receive lp fox), with optional metadata to provide more color.

This is already currently happening already for `addLiquidityEth` and `removeLiquidityEth` as you can see from the unit tests: https://github.com/shapeshift/unchained/blob/e74a4370bf9dd5a3181d2e9056bea76bcf8d462c/node/packages/client/src/ethereum/parser/__tests__/ethereum.test.ts#L796

We can tell that a fee was paid, eth and fox were sent, and fox lp tokens were received. What we don't know from the current parsed transaction that it was parsed by the `uniV2` parser, and what method was called which is what we would be adding to the `data` payload.

**Comment by kaladinlight** [comment]
> @kaladinlight Currently I think there are multiple txs for a stake action right? We probably need to pack those transactions in one for web, because currently the staking tx has only one asset (in my case LP Fox), but the staking is done using two different assets (eth and lp fox).

The parser should only produce one single transaction object per transaction that encompasses multiple possible transfers (ie. send eth and fox, receive lp fox), with optional metadata to provide more color.

This is already currently happening already for `addLiquidityEth` and `removeLiquidityEth` as you can see from the unit tests: https://github.com/shapeshift/unchained/blob/e74a4370bf9dd5a3181d2e9056bea76bcf8d462c/node/packages/client/src/ethereum/parser/__tests__/ethereum.test.ts#L796

We can tell that a fee was paid, eth and fox were sent, and fox lp tokens were received. What we don't know from the current parsed transaction that it was parsed by the `uniV2` parser, and what method was called which is what we would be adding to the `data` payload.

**Comment by stackedq** [comment]
@kaladinlight thanks for the explanation.

**Comment by 0xApotheosis** [comment]
Closed by @vividwood's PR https://github.com/shapeshift/lib/pull/648.
Related web PR: https://github.com/shapeshift/web/pull/1798
