### ISSUE TITLE
Add assetId, chainId to parza layer

### ISSUE THREAD

**Issue by 0xdef1cafe** [shapeshift/unchained#395]
### Overview

Requires

https://github.com/shapeshift/lib/issues/553
https://github.com/shapeshift/lib/issues/549

Same deal as lib, add these to the parza, and once there are no remaining references to caip2 and caip19 we can remove those from the types

### References and additional details

This should be done in the unchained parza layer.

### Acceptance Criteria

We no longer refer to caip2 or caip19 or caip10 in unchained parser.

**Comment by 0xApotheosis** [comment]
There are not many CAIP types in the parser, but there is a lot of CAIP vernacular in our property names.

I've created another issue for this here: https://github.com/shapeshift/unchained/issues/398
