### ISSUE TITLE
Flatten exports from CAIP packages

### ISSUE THREAD

**Issue by 0xApotheosis** [shapeshift/unchained#396]
### Overview

Use flattened exports from the outcome of https://github.com/shapeshift/lib/issues/548

### References and additional details

Like https://github.com/shapeshift/web/pull/1591, but for `unchained`.

### Acceptance Criteria

Functions like `toCAIP19` or `fromCAIP19` are imported directly from the CAIP packages.

**Comment by kaladinlight** [comment]
Now tracked in lib: https://github.com/shapeshift/lib/issues/619
