### ISSUE TITLE
Replace CAIP property names in the parser with generic names (`assetId`, `chainId`, etc)

### ISSUE THREAD

**Issue by 0xApotheosis** [shapeshift/unchained#398]
### Overview

We use CAIP vernacular in our parsing logic, including on transactions, transfers, fees etc. 

Rename these to their more generic equivalents.

### References and additional details

E.g. https://github.com/shapeshift/unchained/blob/650ce054bf30e923c858a01f2096d4322f8419f6/node/packages/client/src/types.ts#L7

This will be a multi-PR process:

1. `unchained`: Add additional types alongside existing types: (https://github.com/shapeshift/unchained/pull/404)
1. `lib`: Add additional types alongside existing types: https://github.com/shapeshift/lib/pull/587
1. `web`: Update logic to point to new property names
1. `unchained`: Remove deprecated properties

### Acceptance Criteria

We no longer use CAIP vernacular in `unchained` parser.

**Comment by kaladinlight** [comment]
Issue now tracked in lib: https://github.com/shapeshift/lib/issues/618
