### ISSUE TITLE
websocket client doesn't throw on failed connection

### ISSUE THREAD

**Issue by 0xdef1cafe** [shapeshift/unchained#400]
### Overview

If the websocket fails to connect - it never actually resolves/rejects the promise. Accordingly, the client consuming the websocket (web) isn't actually able to try/catch as the promise never resolves.

### References and additional details

See here for potential fix https://github.com/shapeshift/unchained/commit/5234dc985cf85afd3acb1c13b0d1925a4595b779

### Acceptance Criteria

If the websocket fails to connect - it should reject the promise so the consumer is able to gracefully handle errors and not hang.

**Comment by kaladinlight** [comment]
Related issue: https://github.com/shapeshift/unchained/issues/136
