### ISSUE TITLE
Use k8s spot termination handler

### ISSUE THREAD

**Issue by kaladinlight** [shapeshift/unchained#41]
https://github.com/pusher/k8s-spot-termination-handler

Currently, spot inst termination signals are not caught and handled resulting in corrupted dbs during sync if nodes churn.

AC:
- Handle spot termination signal and gracefully shutdown pods

**Comment by samortaylor** [comment]
Added AWS node termination handler helm chart to cluster-launcher:
https://github.com/shapeshift/cluster-launcher/pull/8

Will be deploying this to unchained shortly
