### ISSUE TITLE
Automated EBS snapshotting and restore

### ISSUE THREAD

**Issue by kaladinlight** [shapeshift/unchained#42]
Instead of manually managing snapshotting and restore, we want this to be an automated process.

https://aws.amazon.com/blogs/containers/using-ebs-snapshots-for-persistent-storage-with-your-eks-cluster/

AC:
- Automate snapshotting on a regular schedule
- Restore stateful set from snapshot if brand new
- Clean up old snapshots to avoid burning $$$

**Comment by 0xdef1cafe** [comment]
closing unless this becomes a maintenance burden in the future and could be bountied to @samortaylor
