### ISSUE TITLE
Abstract EVM logic

### ISSUE THREAD

**Issue by kaladinlight** [shapeshift/unchained#432]
### Overview

With the addition of layer 2 chains and current eth support, we will ideally want to leverage as much shared code across the coinstacks as makes sense

### References and additional details

coinstacks/common/evm

### Acceptance Criteria

- Shared logic is pulled out into common/evm for use across all evm chains

**Comment by 0xdef1cafe** [comment]
let's copypasta now and do this on the third evm chain
