### ISSUE TITLE
abstract shared evm logic

### ISSUE THREAD

**Issue by kaladinlight** [shapeshift/unchained#441]
### Overview

currently ethereum and avalanche are direct copies of one another. I had attempted abstracting the controllers directly, but this was made difficult with the way the routes are generated via tsoa. An alternative would be just lifting out the logic for each route handler so that they can be shared across coinstacks.

### References and additional details

- coinstacks/avalanche/api
- coinstacks/ethereum/api

### Acceptance Criteria

- dedupe shared evm logic

**Comment by 0xdef1cafe** [comment]
useful and important, keeping
