### ISSUE TITLE
create and expose evm base types/interfaces

### ISSUE THREAD

**Issue by kaladinlight** [shapeshift/unchained#442]
### Overview

to prevent the need for type unions in the client side abstract evm packages, it would be ideal to create a base evm type/interface set that each evm coinstack can extend from if needed and expose this for client use

### References and additional details

- coinstacks/common/api/evm

### Acceptance Criteria

- create, use, and expose base evm types/interfaces

**Comment by 0xdef1cafe** [comment]
same as https://github.com/shapeshift/unchained/issues/441 useful and important
