### ISSUE TITLE
Avalanche performance analysis

### ISSUE THREAD

**Issue by kaladinlight** [shapeshift/unchained#460]
### Overview

It was noticed that account endpoints are really slow when querying blockbook. A second instance just finished syncing that we can test if it was a bad initial sync due to a stay synced error, or if we need to dig into the runtime code more to figure out where the bottle-neck is.

### References and additional details

- https://dev-api.avalanche.shapeshift.com/docs/#/v1/GetAccount
- https://dev-api.avalanche.shapeshift.com/docs/#/v1/GetTxHistory

### Acceptance Criteria

- Determine where the performance bottle-neck is
- Outline the path forward to fix

**Comment by 0xdef1cafe** [comment]
the bandaid in https://github.com/shapeshift/web/issues/2231 seems sufficient for now - can reopen if users report issues with large tx histories on avalanche
