### ISSUE TITLE
Add Optimism Support for Blockbook

### ISSUE THREAD

**Issue by kaladinlight** [shapeshift/unchained#568]
### Overview

We use blockbook to index eth/evm chains, add support for indexing optimism

### References and additional details

https://community.optimism.io/docs/developers/
https://github.com/trezor/blockbook

### Acceptance Criteria

- Blockbook able to sync optimism L1 data

**Comment by 8888-eth** [comment]
be aware that present optimism data doesn't include real genesis data. 
Please see this : https://community.optimism.io/docs/useful-tools/explorers/#access-to-pre-regenesis-history

It had 3 phases of pre-generated genesis history.
