### ISSUE TITLE
Sync Geth Archive Node

### ISSUE THREAD

**Issue by kaladinlight** [shapeshift/unchained#569]
### Overview

To support full historical queries and internal transaction tracing, we need to provide archive nodes. These will be leveraged when blockbook 0.4.0 is release which brings substantial eth improvements including: contract indexing, nft support, and internal transaction indexing

### References and additional details

https://ethereum.org/en/developers/docs/nodes-and-clients/

### Acceptance Criteria

- geth archive node

**Comment by 8888-eth** [comment]
I think erigon will give more fast sync than geth with ACID. 

ref: https://github.com/ledgerwatch/erigon/wiki/Choice-of-storage-engine
