### ISSUE TITLE
Parse "to" fields in osmosis join-pool transactions

### ISSUE THREAD

**Issue by pastaghost** [shapeshift/unchained#611]
### Overview

The "to" address fields in osmosis join-pool transactions should be correctly parsed from the transfer events.

### References and additional details

See the original comment from @kaladinlight here:

<img width="942" alt="Screenshot 2023-01-30 at 1 13 01 PM" src="https://user-images.githubusercontent.com/62026038/215635524-b236f342-3246-4335-bff4-13e98225168b.png">

### Acceptance Criteria

"to" address fields in osmosis join-pool transactions are correctly parsed from the transfer events. This should be confirmed by updated tests in an corresponding unchained-client PR.

**Comment by kaladinlight** [comment]
Additional reference: https://github.com/shapeshift/unchained/issues/553
