### ISSUE TITLE
Prevent stateful set recreation if PVC already exists

### ISSUE THREAD

**Issue by lmyslinski** [shapeshift/unchained#776]
### Overview

Whenever we run our backup, statefulset gets restarted manually without a PVC attached, which results in the next commit to trigger a replacement of the statefulset due to changes in configuration. This effectively reloads all of our infrastructure whenever a backup is made. 

### References and additional details

- make sure not to add a PVC in the pulumi config if one already exists with given config

### Acceptance Criteria

 `sts` are not replaced after a backup is made

**Comment by kaladinlight** [comment]
automated snapshots turned off at this time
