### ISSUE TITLE
Add blockbook support for Arbitrum

### ISSUE THREAD

**Issue by lmyslinski** [shapeshift/unchained#783]
### Overview

[blockbook](https://github.com/trezor/blockbook) currently does not support Arbitrum, we'll have to patch our fork or try to get it merged upstream.

### References and additional details

https://github.com/trezor/blockbook/issues/668

### Acceptance Criteria

* Blockbook running correctly with Arbitrum support

**Comment by hardiktheprogrammer** [comment]
@lmyslinski I would Like to work on this I understand the whole code 
my discord id Haardik#5890

**Comment by kaladinlight** [comment]
https://github.com/kaladinlight/blockbook/tree/add-arbitrum
