### ISSUE TITLE
Polygon: Erigon support

### ISSUE THREAD

**Issue by kaladinlight** [shapeshift/unchained#895]
### Overview

Bor + Heimdall has been very unstable and is pretty costly as far as volume/resource requirements. Erigon may be a more suitable replacement

### References and additional details

https://github.com/ledgerwatch/erigon
https://wiki.polygon.technology/docs/pos/operate/node/erigon-client/

### Acceptance Criteria

- Spin up an erigon node from snapshot
- Validate stability and cost and determine if we should cut over

**Comment by martinboehm** [comment]
@kaladinlight Cool, let me know, how it goes, I would be very interested :)

**Comment by kaladinlight** [comment]
> @kaladinlight Cool, let me know how it goes, I would be very interested :)

I will be sure to update you as I have time to finish standing things up. As a side note, I updated our ethereum full nodes to use pebbledb + path based storage scheme and reduced storage size from ~3TB -> ~1TB. The sync was surprisingly quick for a fresh full sync as well and things have been smooth and stable since the cut over.

BSC v1.3.x brings in path based storage, so I was planning on doing the same test and cut over there to reduce disk space and hopefully bring some added stability as well. I am hoping polygon brings this into bor sooner than later as an alternative if erigon isn't found to be suitable for any reason.

**Comment by martinboehm** [comment]
@kaladinlight We are running our Ethereum archive nodes on Erigon and the DB size dropped from 12T to 2.5T. The full sync was also really fast. So far it works well..
