### ISSUE TITLE
[Spike] rethink our backend infra

### ISSUE THREAD

**Issue by 0xean** [shapeshift/unchained#904]
### Overview

Unchained is currently very expensive to run and maintain.  If we consider labor and AWS costs, we are spending something around 40K / month on it.  Its reliability has been spotty at best, between underlying node issues, mysterious timeouts and database corruptions during syncing its worth us collectively evaluating its suitability for our use case. Customers are frustrated with the reliability of our application and we are delaying the launch of features in order to test them against a known working backend.  While running our own nodes could be a valuable service, if those nodes aren't stable enough and don't offer enough redundancy for production use, we aren't providing any value and spending significant DAO resources to do it. 

The basic needs of our application could potentially be served from a variety of different providers who have much better guarantees around uptime (>99.9%) and are far more cost effective (< 1k / month). There may not exist a single provider that offers all of the chains that we require, and we may still choose to provide an abstraction over their APIs to simplify implementation, but regardless this issue has to be addressed.

### References and additional details

Potential providers:

- NowNodes - offers [nodes](https://nownodes.io/nodes) + [blockbooks / explorers](https://documenter.getpostman.com/view/13630829/TVmFkLwy#cb42db8b-7846-41a6-9a67-7162b4a27667) for several of the chains we currently support
- Chainstack - offers nodes + hosted subgraphs for EVMs

### Acceptance Criteria

The output of this spike should be the following

- cost / benefit analysis of moving to hosted solutions for our nodes and indexed blockchain 
- cost / benefit analysis on abstracting away the underlying providers APIs behind our own existing unchained API vs direct integration
- suggestions for a migration plan that include incremental cutover and what nodes / indexer's we may need to maintain (like thorchain)
- optional: suggestions to resolve the reliability issues we are experiencing with the unchained stack

**Comment by 0xean** [comment]
Below is a summary of the current chains we support and options for obtaining that data.

It is important to highlight that NowNodes is incredibly eager to work with us and would probably be willing to add support for the missing EVMs that have nodes for, but no explorer or WSS support. This would potentially mean we could rely on one provider for everything with the exception of thorchain that we could host ourselves for the time being.

NowNodes has additional chains that we have also deprecated in the past due to the inability to justify the expense (osmo for example). 

Not only would this unlock ~25,000 / a month in cost savings it also means that new chains could be added with a much smaller lift in the future


Chains | Blockbook / Indexed Data | Node | WSS support
-- | -- | -- | --
ETH | NowNodes | NowNodes | Yes
Polygon | NowNodes | NowNodes | Yes
Gnosis | Chainstack Subgraph | Chainstack | Yes
Optimism | Chainstack Subgraph | Chainstack | Yes
BNB Smart Chain | Chainstack Subgraph | Chainstack | Yes
Arbitrum One | NowNodes | NowNodes | No
BTC | NowNodes | NowNodes | Yes
BCH | NowNodes | NowNodes | Yes
LTC | NowNodes | NowNodes | Yes
DOGE | NowNodes | NowNodes | Yes
Avalanche | NowNodes | NowNodes | Yes
Cosmos | NowNodes | NowNodes | No
Thorchain |   |   |  
  |   |   |

**Comment by twblack88** [comment]
Worth cost evals on 1inch, infura, and (sigh) the graph

**Comment by 0xean** [comment]
Open Questions:

- do we require WSS connections directly to blockbooks

**Comment by kaladinlight** [comment]
Moving forward with nownodes at this time. Calling this spike done.
