### ISSUE TITLE
Base spike

### ISSUE THREAD

**Issue by 0xean** [shapeshift/unchained#973]
- determine level of effort to get blockbook support for BASE 
-

**Comment by kaladinlight** [comment]
Base is essentially an Optimism clone which means we have references for implementation along with the github repo: https://github.com/base-org/node.

The below estimations are conservative to account for any unknown unknowns at this time.

Unchained:
- Node support: 5 (sync time is separate - there are public snapshot available for bootstrapping)
- Blockbook support: 3 (sync time is separate)
- API support: 3


Web:
  - Basic support: 3
  - Swap support (OneInch, LiFi): 5
  - NFT support (zapper, zerion, covalent, alchemy): 1
 
We can leverage nownodes if they expose websockets, but this will add significant request overhead to sync our blockbook instances against nownodes nodes. Worthwhile to test and validate blockbook fully while we are syncing a node, but I would recommend we run our own nodes until they add official blockbook support on their end. This would fit nicely with optimism blockbook support provided by nownodes if they have the appetite imo.

**Comment by 0xean** [comment]
will sync with NN on wednesday and determine their level of interest before we decide to take this in house.

**Comment by kaladinlight** [comment]
Moving forward with standing up base in unchained.
